name: 'Build B2C Custom Policy Files'
description: ''
author: 'Nick Drazenovic'

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: 'book-open'
  color: 'blue'

# Define your inputs here.
inputs:
  environment: # id of input
    description: 'What environment from appsettings.json to build for'
    required: true
  inputFolder:
    description:
      'Folder containing the XML policy files and the appsettings.json file'
    required: true
  outputFolder:
    description:
      'Folder to put the resulting compiled policy files into (will be created
      if does not exist)'
    required: true

# Define your outputs here.
outputs:
  result:
    description: 'Boolean result indicating success'

runs:
  using: node20
  main: dist/index.js
